name: Compilar APK de Flet
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Inicializar y Compilar Proyecto APK
        run: |
          # Forzamos la creación del paquete móvil ignorando advertencias de estructura
          flet build apk pcphone.py

      - name: Guardar APK como Resultado
        uses: actions/upload-artifact@v4
        with:
          name: juego-agilidad-android
          # Buscamos el APK en cualquier subcarpeta generada por el build de flet
          path: build/apk/*.apk
