name: Compilar APK de Flet
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.0' # Forzamos una versión ultra-estable compatible con Flet

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Crear Estructura de Compilación Móvil
        run: |
          # Inicializamos el build de flet para crear los manifiestos de Android correctamente
          flet build apk --manifest-only

      - name: Compilar APK Final
        run: |
          # Compilamos el APK apuntando directamente a nuestro script principal
          flet build apk pcphone.py

      - name: Guardar APK como Resultado
        uses: actions/upload-artifact@v4
        with:
          name: juego-agilidad-android
          path: build/apk/*.apk
